In [2]:
import pandas
import numpy as np
import pprint

pretty = pprint.PrettyPrinter(indent=4)

obj2 = pandas.Series([4, 7, -5, 2], index=['a', 'b', 'c', 'd'])

sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj3 = pandas.Series(sdata)

for elem in obj3:
    print(elem, '\n')

obj3

35000 

71000 

16000 

5000 



Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [3]:

obj4 = pandas.Series(sdata, index=states)  # Utah is left out

# print(obj2[['a', 'c']])
# print(obj2[obj2 > 2])
# print(pandas.isnull(obj4))
# print(pandas.notnull(obj4))
# print('\n\n')

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
new_column_order = ['year', 'state', 'pop']
frame1 = pandas.DataFrame(data)
frame2 = pandas.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                          index=['one', 'two', 'three', 'four', 'five', 'six'])
# print(frame)
# simple to swap columns
frame = pandas.DataFrame(data, columns=new_column_order)
# print(frame)
states = frame['state']
# print('\nstates: \n', states)
# print('\n', frame2)

frame2['debt'] = 19
frame2

year   state  pop  debt
one    2000    Ohio  1.5    19
two    2001    Ohio  1.7    19
three  2002    Ohio  3.6    19
four   2001  Nevada  2.4    19
five   2002  Nevada  2.9    19
six    2003  Nevada  3.2    19

In [4]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [5]:
v = pandas.Series([-2,5,77], index=['one', 'four', 'six'])
frame2['debt'] = v
frame2

year   state  pop  debt
one    2000    Ohio  1.5  -2.0
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   5.0
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2  77.0

In [6]:
# dynamically craete a new column using an expression to do vectorization <3
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5  -2.0     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   5.0    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2  77.0    False

In [7]:
# delete the previously created column
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [8]:
pop = {
    'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}
}
frame3 = pandas.DataFrame(pop)
# Transpose
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [9]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [10]:
pdata = {
    'Ohio': frame3['Ohio'][:2],
    'Nevada': frame3['Nevada'][:-1]
}

pandas.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [11]:
# we can set the index and column names
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [12]:
# .values works w/dataframes and series
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [13]:
checks = [
    'Ohio' in frame3.columns, 2002 in frame3.index,
    'California' in frame3.columns, 2021 in frame3.index
]
checks

[True, True, False, False]

In [14]:
# pandas indexes are like fixed-width python sets, but allow dupes
idx = pandas.Index(['foo', 'foo', 'bar', 'bar', 'tro'])
idx2 = pandas.Index(['per', 'cep', 'bar', 'per'])

ops = [
    idx, idx2,
    # set like ops
    idx.append(idx2),
    idx.difference(idx2),
    idx.intersection(idx2),
    idx.union(idx2),
    idx.isin(idx2),
    idx.delete(2),
    idx.drop('foo'),
    #idx.insert('tro', 2), # not sure how to do this one
    idx.is_monotonic,
    idx.is_unique,
    idx.unique()
]
ops

[Index(['foo', 'foo', 'bar', 'bar', 'tro'], dtype='object'),
 Index(['per', 'cep', 'bar', 'per'], dtype='object'),
 Index(['foo', 'foo', 'bar', 'bar', 'tro', 'per', 'cep', 'bar', 'per'], dtype='object'),
 Index(['foo', 'tro'], dtype='object'),
 Index(['bar'], dtype='object'),
 Index(['bar', 'bar', 'cep', 'foo', 'foo', 'per', 'per', 'tro'], dtype='object'),
 array([False, False,  True,  True, False]),
 Index(['foo', 'foo', 'bar', 'tro'], dtype='object'),
 Index(['bar', 'bar', 'tro'], dtype='object'),
 False,
 False,
 Index(['foo', 'bar', 'tro'], dtype='object')]

In [15]:
obj = pandas.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [16]:
# re-index
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [17]:
obj3 = pandas.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [18]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [19]:
ra1 = np.arange(9).reshape(3,3)
frame = pandas.DataFrame(
    ra1, index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California']
)
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [20]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [21]:
states = ['Texas', 'Utah', 'California']
frame.reindex(states)

Ohio  Texas  California
Texas        NaN    NaN         NaN
Utah         NaN    NaN         NaN
California   NaN    NaN         NaN

In [22]:
# frame.loc[['a','b','c','d'], states] # won't work anymore

obj = pandas.Series(np.arange(5.), index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [23]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [24]:
obj.drop(['d', 'c'])
data = pandas.DataFrame(np.arange(16).reshape((4, 4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])
cdata = data.copy()
drop1 = data.drop('Utah')
# axis=1 means columns
drop2 = data.drop(['three', 'four'], axis=1)
drop3 = data.drop(['two'], axis=1)
# drop in place
data.drop(['Utah'], axis=0, inplace=True)
drop_set = [data, cdata, drop1, drop2, drop3, data]
# drop_set
data
cdata
drop1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

# Indexing, Selection, & Filtering for DataFrames and Series

In [25]:
obj = pandas.Series(np.arange(10) * 5.75, index=['a','b','c','d','e','f','g','h','i','j'])
index_select_filter = [
    obj, obj[1], obj[['b']],
    obj[['a','e','j']],
    obj[2:5],
    obj[obj > 5],
    obj['h':'j'],
]
obj['a':'c'] = 5
index_select_filter

[a     5.00
 b     5.00
 c     5.00
 d    17.25
 e    23.00
 f    28.75
 g    34.50
 h    40.25
 i    46.00
 j    51.75
 dtype: float64,
 5.75,
 b    5.75
 dtype: float64,
 a     0.00
 e    23.00
 j    51.75
 dtype: float64,
 c     5.00
 d    17.25
 e    23.00
 dtype: float64,
 b     5.75
 c    11.50
 d    17.25
 e    23.00
 f    28.75
 g    34.50
 h    40.25
 i    46.00
 j    51.75
 dtype: float64,
 h    40.25
 i    46.00
 j    51.75
 dtype: float64]

In [26]:
data = pandas.DataFrame(np.arange(16).reshape(4,4),
                     index=['Ohio', 'Colorado', 'Utah', 'New York'],
                     columns=['one', 'two', 'three', 'four'])
index_select_filter = [
    data,
    # select columns
    data[['two']],
    data[['three', 'four']],
    # a few special cases that'll select rows
    data[:2], # select 1st two rows
    data[data['three'] > 4], # boolean array
]
index_select_filter

[          one  two  three  four
 Ohio        0    1      2     3
 Colorado    4    5      6     7
 Utah        8    9     10    11
 New York   12   13     14    15,
           two
 Ohio        1
 Colorado    5
 Utah        9
 New York   13,
           three  four
 Ohio          2     3
 Colorado      6     7
 Utah         10    11
 New York     14    15,
           one  two  three  four
 Ohio        0    1      2     3
 Colorado    4    5      6     7,
           one  two  three  four
 Colorado    4    5      6     7
 Utah        8    9     10    11
 New York   12   13     14    15]

In [42]:
# boolean DataFrame
data < 10

Qu1   Qu2   Qu3
0  True  True  True
1  True  True  True
2  True  True  True
3  True  True  True
4  True  True  True

In [43]:
# set all vals < 5 to 0
data[data < 5] = 0
data

Qu1  Qu2  Qu3
0    0    0    0
1    0    0    5
2    0    0    0
3    0    0    0
4    0    0    0

In [29]:
data.loc['Ohio', 'two'] = 22
# select column `two` and `three` from the Colorado column index
loc_iloc = [
    data,
    data.loc['Colorado', ['two', 'three']],
    data.iloc[2, [3,0,1]],
    # select Utah row
    data.iloc[2],
    # select rows [Colorado, Utah] col [four, one, two]
    data.iloc[[1,2], [3,0,1]],
    data.loc[:'Utah', 'one':'three'],
    data.loc[:'Utah', 'two'],
    data.iloc[:, :3][data['three'] > 5]
]
loc_iloc

[          one  two  three  four
 Ohio        0   22      0     0
 Colorado    0    5      6     7
 Utah        8    9     10    11
 New York   12   13     14    15,
 two      5
 three    6
 Name: Colorado, dtype: int64,
 four    11
 one      8
 two      9
 Name: Utah, dtype: int64,
 one       8
 two       9
 three    10
 four     11
 Name: Utah, dtype: int64,
           four  one  two
 Colorado     7    0    5
 Utah        11    8    9,
           one  two  three
 Ohio        0   22      0
 Colorado    0    5      6
 Utah        8    9     10,
 Ohio        22
 Colorado     5
 Utah         9
 Name: two, dtype: int64,
           one  two  three
 Colorado    0    5      6
 Utah        8    9     10
 New York   12   13     14]

### Using pandas.DataFrame.add()

In [30]:
df1 = pandas.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pandas.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [31]:
equivalents = [
    1 / df1,
    df1.rdiv(1)
]
equivalents

[       a         b         c         d
 0    inf  1.000000  0.500000  0.333333
 1  0.250  0.200000  0.166667  0.142857
 2  0.125  0.111111  0.100000  0.090909,
        a         b         c         d
 0    inf  1.000000  0.500000  0.333333
 1  0.250  0.200000  0.166667  0.142857
 2  0.125  0.111111  0.100000  0.090909]

### Operations between DataFrame and Series

In [32]:
arr = np.arange(12.).reshape(3,4)
np_broadcasting = [
    arr,
    arr[0],
    # broadcasting operation
    arr - arr[0]
]
np_broadcasting

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([0., 1., 2., 3.]),
 array([[0., 0., 0., 0.],
        [4., 4., 4., 4.],
        [8., 8., 8., 8.]])]

In [33]:
# broadcasting is similar with dataframes and series
frame = pandas.DataFrame(np.arange(12.).reshape((4, 3)),
                         columns=list('bde'),
                         index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
series2 = pandas.Series(range(3), index=list('bef'))
series3 = frame['d']
frame_series_broadcasting = [
    frame, '','',
    series, '','',
    frame - series, '','',
    # will re-index and union
    frame + series2, '','',
    frame.sub(series3, axis='index')
]
frame_series_broadcasting

[          b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0,
 '',
 '',
 b    0.0
 d    1.0
 e    2.0
 Name: Utah, dtype: float64,
 '',
 '',
           b    d    e
 Utah    0.0  0.0  0.0
 Ohio    3.0  3.0  3.0
 Texas   6.0  6.0  6.0
 Oregon  9.0  9.0  9.0,
 '',
 '',
           b   d     e   f
 Utah    0.0 NaN   3.0 NaN
 Ohio    3.0 NaN   6.0 NaN
 Texas   6.0 NaN   9.0 NaN
 Oregon  9.0 NaN  12.0 NaN,
 '',
 '',
           b    d    e
 Utah   -1.0  0.0  1.0
 Ohio   -1.0  0.0  1.0
 Texas  -1.0  0.0  1.0
 Oregon -1.0  0.0  1.0]

## Function Application and Mapping

In [34]:
def max_minus_min(x):
    debug = 1
    return x.max() - x.min()

def min_max_series(x):
    debug = 1
    return pandas.Series([x.min(), x.max()], index=['min', 'max'])

lambda_format = lambda x: '%.2f' % x

frame = pandas.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                         index=['Utah', 'Ohio', 'Texas', 'Oregon'])
function_maps = [
    frame, '','',
    # np.abs() will make all the values positive
    #np.abs(frame), '','',
    # apply a function to each column of $frame
    frame.apply(max_minus_min, axis='index'), '','',
    # apply a function to each row of $frame
    frame.apply(max_minus_min, axis='columns'), '','',
    # apply a function that returns a series
    frame.apply(min_max_series), '','frame.applymap(lambda_format)',
    # using .applymap(), this functions works on all cells in the df
    frame.applymap(lambda_format), '','',
    # compare the difference to .map(), this gets called on a single column
    frame['e'].map(lambda_format)
]
function_maps

[               b         d         e
 Utah    0.045656  0.823883 -0.805217
 Ohio   -1.705230  0.523225 -0.435102
 Texas  -0.746488  1.833214  0.860381
 Oregon  0.594310 -2.361818  1.736737,
 '',
 '',
 b    2.299540
 d    4.195031
 e    2.541953
 dtype: float64,
 '',
 '',
 Utah      1.629099
 Ohio      2.228455
 Texas     2.579702
 Oregon    4.098555
 dtype: float64,
 '',
 '',
            b         d         e
 min -1.70523 -2.361818 -0.805217
 max  0.59431  1.833214  1.736737,
 '',
 'frame.applymap(lambda_format)',
             b      d      e
 Utah     0.05   0.82  -0.81
 Ohio    -1.71   0.52  -0.44
 Texas   -0.75   1.83   0.86
 Oregon   0.59  -2.36   1.74,
 '',
 '',
 Utah      -0.81
 Ohio      -0.44
 Texas      0.86
 Oregon     1.74
 Name: e, dtype: object]

## Sorting & Ranking

In [35]:
# sort by index
obj = pandas.Series(range(4), index=['d', 'a', 'b', 'c'])
frame = pandas.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                         columns=['d', 'a', 'b', 'c'])
sorts = [
    obj, '','',
    obj.sort_index(), '','',
    frame, '','',
    frame.sort_index(), '','',
    # sort by columns
    frame.sort_index(axis='columns', ascending=False)
]
sorts

[d    0
 a    1
 b    2
 c    3
 dtype: int64,
 '',
 '',
 a    1
 b    2
 c    3
 d    0
 dtype: int64,
 '',
 '',
        d  a  b  c
 three  0  1  2  3
 one    4  5  6  7,
 '',
 '',
        d  a  b  c
 one    4  5  6  7
 three  0  1  2  3,
 '',
 '',
        d  c  b  a
 three  0  3  2  1
 one    4  7  6  5]

In [36]:
# sort by value
obj = pandas.Series([4, 7, -3, 2])
frame = pandas.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
sorts = [
    obj, '','',
    obj.sort_values(), '','',
    frame, '','',
    frame.sort_values(by='b'), '',"frame.sort_values(by=['a','b'])",
    frame.sort_values(by=['a','b']),
]
sorts

[0    4
 1    7
 2   -3
 3    2
 dtype: int64,
 '',
 '',
 2   -3
 3    2
 0    4
 1    7
 dtype: int64,
 '',
 '',
    b  a
 0  4  0
 1  7  1
 2 -3  0
 3  2  1,
 '',
 '',
    b  a
 2 -3  0
 3  2  1
 0  4  0
 1  7  1,
 '',
 "frame.sort_values(by=['a','b'])",
    b  a
 2 -3  0
 0  4  0
 3  2  1
 1  7  1]

In [37]:
# ranking
obj = pandas.Series([7, -5, 7, 4, 2, 0, 4])
frame = pandas.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],'c': [-2, 5, 8, -2.5]})
ranks = [
    #obj.shape, '','',
    #obj, '','',
    obj.sort_values(), '','',
    #obj.rank(), '','',
    obj.rank().sort_values(), '','',
    obj.rank(method='first').sort_values(), '','',
    obj.rank(ascending=False, method='max').sort_values(), '','',
    frame, '','',
    frame.rank(axis='columns')
]
ranks

[1   -5
 5    0
 4    2
 3    4
 6    4
 0    7
 2    7
 dtype: int64,
 '',
 '',
 1    1.0
 5    2.0
 4    3.0
 3    4.5
 6    4.5
 0    6.5
 2    6.5
 dtype: float64,
 '',
 '',
 1    1.0
 5    2.0
 4    3.0
 3    4.0
 6    5.0
 0    6.0
 2    7.0
 dtype: float64,
 '',
 '',
 0    2.0
 2    2.0
 3    4.0
 6    4.0
 4    5.0
 5    6.0
 1    7.0
 dtype: float64,
 '',
 '',
      b  a    c
 0  4.3  0 -2.0
 1  7.0  1  5.0
 2 -3.0  0  8.0
 3  2.0  1 -2.5,
 '',
 '',
      b    a    c
 0  3.0  2.0  1.0
 1  3.0  1.0  2.0
 2  1.0  2.0  3.0
 3  3.0  2.0  1.0]

## Axis Indexes with Duplicate Labels

In [38]:
obj = pandas.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
df = pandas.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

arr = [
    obj,
    obj.index.is_unique,
    obj['a'],
    obj['c'],
    df.loc['b']
]
arr

[a    0
 a    1
 b    2
 b    3
 c    4
 dtype: int64,
 False,
 a    0
 a    1
 dtype: int64,
 4,
           0         1         2
 b -0.746801 -0.262503 -0.135886
 b  1.534053 -0.434873  0.036667]

# Summarizing and Computing Descriptive Statistics

In [39]:
df = pandas.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                      index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
reductions = [
    df,'','',
    df.sum(), '',"df.sum(axis='columns'",
    df.sum(axis='columns'), '','',
    df.mean(skipna=False, axis='columns'), '','',
    # will return the max index from each column
    df.idxmax(), '','',
    # accumulations
    df.cumsum(), '','',
    df.describe()
]
reductions

[    one  two
 a  1.40  NaN
 b  7.10 -4.5
 c   NaN  NaN
 d  0.75 -1.3,
 '',
 '',
 one    9.25
 two   -5.80
 dtype: float64,
 '',
 "df.sum(axis='columns'",
 a    1.40
 b    2.60
 c    0.00
 d   -0.55
 dtype: float64,
 '',
 '',
 a      NaN
 b    1.300
 c      NaN
 d   -0.275
 dtype: float64,
 '',
 '',
 one    b
 two    d
 dtype: object,
 '',
 '',
     one  two
 a  1.40  NaN
 b  8.50 -4.5
 c   NaN  NaN
 d  9.25 -5.8,
 '',
 '',
             one       two
 count  3.000000  2.000000
 mean   3.083333 -2.900000
 std    3.493685  2.262742
 min    0.750000 -4.500000
 25%    1.075000 -3.700000
 50%    1.400000 -2.900000
 75%    4.250000 -2.100000
 max    7.100000 -1.300000]

### Unique Values, Values Counts, & Membership

In [40]:
obj = pandas.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
to_match = pandas.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pandas.Series(list('cba'))
data = pandas.DataFrame({'Qu1': [1, 3, 4, 3, 4], 'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
v = [
    obj, '',"obj.unique()",
    obj.unique(), '',"obj.value_counts()",
    obj.value_counts(), '','',
    pandas.value_counts(obj.values, sort=False), '',"series.isin()",
    # .isin() practice
    obj.isin(['b','c']), 'obj[objd.is`in(["b","c"])]',
    obj[obj.isin(['b','c'])], ".get_indexer()",
    # .get_indexer() practice
    to_match, '', 'pandas.Index(unique_vals).get_indexer(to_match)',
    pandas.Index(unique_vals).get_indexer(to_match), '', '.apply(pandas.value_counts).fillna(0)',

    # <3 <3 use pandas.value_counts inside frame.apply().fillna(0) <3 <3
    data.apply(pandas.value_counts).fillna(0)
]
v

[0    c
 1    a
 2    d
 3    a
 4    a
 5    b
 6    b
 7    c
 8    c
 dtype: object,
 '',
 'obj.unique()',
 array(['c', 'a', 'd', 'b'], dtype=object),
 '',
 'obj.value_counts()',
 a    3
 c    3
 b    2
 d    1
 dtype: int64,
 '',
 '',
 b    2
 d    1
 a    3
 c    3
 dtype: int64,
 '',
 'series.isin()',
 0     True
 1    False
 2    False
 3    False
 4    False
 5     True
 6     True
 7     True
 8     True
 dtype: bool,
 'obj[objd.is`in(["b","c"])]',
 0    c
 5    b
 6    b
 7    c
 8    c
 dtype: object,
 '.get_indexer()',
 0    c
 1    a
 2    b
 3    b
 4    c
 5    a
 dtype: object,
 '',
 'pandas.Index(unique_vals).get_indexer(to_match)',
 array([0, 2, 1, 1, 0, 2]),
 '',
 '.apply(pandas.value_counts).fillna(0)',
    Qu1  Qu2  Qu3
 1  1.0  1.0  1.0
 2  0.0  2.0  1.0
 3  2.0  2.0  0.0
 4  2.0  0.0  2.0
 5  0.0  0.0  1.0]